### ISSUE TITLE
Add OAuth Support

### ISSUE THREAD

**Issue by tomvoelker** [LSX-UniWue/bibsonomy-zotero-sync#40]
Implement OAuth support for API calls. As all API calls are uniformly made via the `makeBibsonomyRequest` method, this implementation should be straightforward.

## Inspiration
Auth handling in the ChatGPT plugin:
- [plugin_bp.py](https://bitbucket.org/bibsonomy/bibsonomy-llm-scientific-retrieval-plugin/src/main/app/routes/plugin_bp.py)
- [auth.py](https://bitbucket.org/bibsonomy/bibsonomy-llm-scientific-retrieval-plugin/src/main/app/utils/auth.py)

[BibSonomy Documentation](https://www.bibsonomy.org/help_en/OAuth)

## Tasks
- [ ] Implement OAuth workflow via the preferences' pane
- [ ] Implement method for getting the username and storing it
- [ ] Update `makeBibsonomyRequest` method
- [ ] Test and document changes
